# Generated by Django 6.1 on 2026-08-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=25, unique=True)),
                ('vendor', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('vulnerability_name', models.CharField(max_length=255)),
                ('date_added', models.DateField()),
                ('description', models.TextField()),
                ('required_action', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('known_ransomware_use', models.BooleanField(default=False)),
                ('source_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
